version: '3'
services:
  controller:
    build:
      context: .
    working_dir: /home/usero
    container_name: controller
    restart: always
    ports:
      - "20255:20255"
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
      - 1.0.0.1
