services:
  internal-svc:
    image: nginx:latest
    volumes:
      - ./internal/proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - internal
    depends_on:
      - bot
      - app

  app:
    build:
      context: ./internal
      dockerfile: Dockerfile
    networks:
      - internal

  bot:
    build:
      context: ./internal/bot
    environment:
      APPNAME: Admin
      APPURL: http://app:8080/
      APPURLREGEX: ^http://app:8080/.*
      APPFLAG: ITSEC{ab6a4967473a7720a70523f5fa0a24db}
      APPLIMIT: 2
      APPLIMITTIME: 60
    networks:
      - internal

  public:
    build:
      context: ./public
    networks:
      - internal
    depends_on:
      - app
    ports:
      - "50001:8081"

networks:
  internal:
